services:
  bot:
    build:
      context: ./docker-bot
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8504:8504

  yt-whisper:
    build:
      context: ./yt-whisper
      dockerfile: Dockerfile
    ports:
      - 8503:8503
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
